# Generated by Django 5.1.3 on 2024-12-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kurs nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqit")),
            ],
            options={
                'verbose_name': 'kurs ',
                'verbose_name_plural': 'kurslar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dars nomi')),
                ('teacher', models.CharField(max_length=100, verbose_name="O'qituvchi ismi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dars haqida')),
                ('starts_from', models.TimeField(auto_now_add=True, verbose_name='Boshlanish vaqti')),
                ('photo', models.ImageField(upload_to='lessons/photos')),
                ('student_count', models.IntegerField(verbose_name='Talabalar soni')),
                ('price', models.IntegerField(verbose_name='narxi')),
                ('is_available', models.BooleanField(default=True, verbose_name='bor yoki yoq')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name="Bog'langan kurs")),
            ],
            options={
                'verbose_name': 'dars ',
                'verbose_name_plural': 'darslar',
            },
        ),
    ]
