# Generated by Django 5.1.3 on 2024-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='starts_from',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
