# Generated by Django 5.1.3 on 2024-12-20 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_starts_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='starts_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti'),
        ),
    ]
