# Generated by Django 5.1.3 on 2024-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_starts_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='starts_from',
            field=models.DateTimeField(default='2024-01-01 08:00', verbose_name='Boshlanish vaqti'),
        ),
    ]
