# Generated by Django 5.1.3 on 2024-12-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_starts_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-starts_from',), 'verbose_name': 'dars ', 'verbose_name_plural': 'darslar'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starts_from',
            field=models.DateTimeField(default='2024, 1, 1, 8, 0', verbose_name='Boshlanish vaqti'),
        ),
    ]
