# Generated by Django 5.1.3 on 2024-12-25 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_options_alter_lesson_starts_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='starts_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 8, 0), verbose_name='Boshlanish vaqti'),
        ),
    ]
