# Generated by Django 5.1.3 on 2024-12-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_starts_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/photos'),
        ),
    ]
